Решены проблемы билда:                               var long = stream.GetULong();                                     ^ ..\Common\wordcopypaste.js:3412: ERROR - Parse error. identifier is a reserved word                                 for(var j = 0; j < long; ++j)                                                    ^ ..\Common\wordcopypaste.js:3412: ERROR - Parse error. missing ; before statement                                 for(var j = 0; j < long; ++j)
git-svn-id: svn://192.168.3.15/activex/AVS/Sources/TeamlabOffice/trunk/OfficeWeb@50276 954022d7-b5bf-4e40-9824-e11837661b57